# Generated by Django 3.0.10 on 2020-12-03 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0011_auto_20180108_0706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternativename',
            name='is_preferred',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='alternativename',
            name='kind',
            field=models.CharField(choices=[('name', 'Name'), ('abbr', 'Abbreviation'), ('link', 'Link'), ('iata', 'IATA (Airport) Code'), ('icao', 'ICAO (Airport) Code'), ('faac', 'FAAC (Airport) Code')], db_index=True, default='name', max_length=4),
        ),
        migrations.AlterField(
            model_name='alternativename',
            name='language_code',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='alternativename',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
