# Generated by Django 3.0.11 on 2020-12-16 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0012_auto_20201203_0710'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='name_de',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='ascii name'),
        ),
        migrations.AddField(
            model_name='city',
            name='name_en',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='ascii name'),
        ),
        migrations.AddField(
            model_name='city',
            name='name_fr',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='ascii name'),
        ),
        migrations.AddField(
            model_name='city',
            name='name_ru',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='ascii name'),
        ),
        migrations.AddField(
            model_name='city',
            name='name_std_de',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='standard name'),
        ),
        migrations.AddField(
            model_name='city',
            name='name_std_en',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='standard name'),
        ),
        migrations.AddField(
            model_name='city',
            name='name_std_fr',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='standard name'),
        ),
        migrations.AddField(
            model_name='city',
            name='name_std_ru',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='standard name'),
        ),
        migrations.AddField(
            model_name='continent',
            name='name_de',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='ascii name'),
        ),
        migrations.AddField(
            model_name='continent',
            name='name_en',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='ascii name'),
        ),
        migrations.AddField(
            model_name='continent',
            name='name_fr',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='ascii name'),
        ),
        migrations.AddField(
            model_name='continent',
            name='name_ru',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='ascii name'),
        ),
        migrations.AddField(
            model_name='country',
            name='name_de',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='ascii name'),
        ),
        migrations.AddField(
            model_name='country',
            name='name_en',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='ascii name'),
        ),
        migrations.AddField(
            model_name='country',
            name='name_fr',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='ascii name'),
        ),
        migrations.AddField(
            model_name='country',
            name='name_ru',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='ascii name'),
        ),
        migrations.AddField(
            model_name='district',
            name='name_de',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='ascii name'),
        ),
        migrations.AddField(
            model_name='district',
            name='name_en',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='ascii name'),
        ),
        migrations.AddField(
            model_name='district',
            name='name_fr',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='ascii name'),
        ),
        migrations.AddField(
            model_name='district',
            name='name_ru',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='ascii name'),
        ),
        migrations.AddField(
            model_name='district',
            name='name_std_de',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='standard name'),
        ),
        migrations.AddField(
            model_name='district',
            name='name_std_en',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='standard name'),
        ),
        migrations.AddField(
            model_name='district',
            name='name_std_fr',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='standard name'),
        ),
        migrations.AddField(
            model_name='district',
            name='name_std_ru',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='standard name'),
        ),
        migrations.AddField(
            model_name='region',
            name='name_de',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='ascii name'),
        ),
        migrations.AddField(
            model_name='region',
            name='name_en',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='ascii name'),
        ),
        migrations.AddField(
            model_name='region',
            name='name_fr',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='ascii name'),
        ),
        migrations.AddField(
            model_name='region',
            name='name_ru',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='ascii name'),
        ),
        migrations.AddField(
            model_name='region',
            name='name_std_de',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='standard name'),
        ),
        migrations.AddField(
            model_name='region',
            name='name_std_en',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='standard name'),
        ),
        migrations.AddField(
            model_name='region',
            name='name_std_fr',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='standard name'),
        ),
        migrations.AddField(
            model_name='region',
            name='name_std_ru',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='standard name'),
        ),
        migrations.AddField(
            model_name='subregion',
            name='name_de',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='ascii name'),
        ),
        migrations.AddField(
            model_name='subregion',
            name='name_en',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='ascii name'),
        ),
        migrations.AddField(
            model_name='subregion',
            name='name_fr',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='ascii name'),
        ),
        migrations.AddField(
            model_name='subregion',
            name='name_ru',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='ascii name'),
        ),
        migrations.AddField(
            model_name='subregion',
            name='name_std_de',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='standard name'),
        ),
        migrations.AddField(
            model_name='subregion',
            name='name_std_en',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='standard name'),
        ),
        migrations.AddField(
            model_name='subregion',
            name='name_std_fr',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='standard name'),
        ),
        migrations.AddField(
            model_name='subregion',
            name='name_std_ru',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='standard name'),
        ),
    ]
